- name: 'Manage Apache Deployment'
  host: redhat
  become: true
  gather_facts: false
  tasks:
    - name: 'Install Apache Webserver'
      ansible.builtin.package:
        name: 'httpd'
        state: 'present'
    - name: 'Start and enable web Server'
      ansible.builtin.service:
        name: 'httpd'
        state: 'started'
        enable: true
